name: Build Notebooks
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install jupytext nbconvert

      - name: Build notebooks
        run: |
          #
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update part_1/solution.py
          jupytext --to ipynb --update-metadata '{"jupytext":{"cell_metadata_filter":"all"}}' --update part_1/solution.py --output part_1/exercise.ipynb

          jupyter nbconvert part_1/solution.ipynb --ClearOutputPreprocessor.enabled=True --TagRemovePreprocessor.enabled=True --TagRemovePreprocessor.remove_cell_tags task --to notebook --output solution.ipynb
          jupyter nbconvert part_1/exercise.ipynb --ClearOutputPreprocessor.enabled=True --TagRemovePreprocessor.enabled=True --TagRemovePreprocessor.remove_cell_tags solution --to notebook --output exercise.ipynb
          # Convert the cleaned-up exercise.ipynb back to a Python script
          jupytext --to py:percent part_1/exercise.ipynb
          # TODO - do the same for part 2

      - uses: EndBug/add-and-commit@v9
        with:
          add: part_1/solution.ipynb part_1/exercise.ipynb